---
title: "R Notebook"
output: html_notebook
---

```{r}
#install.packages(c("tidyverse", "dslabs"))
library(tidyverse)
library(dslabs)
```

Functions and Objects

```{r}
# y= β_0+ β_1 〖x_1〗^2+ β_2 x_2

b0 <-  2
b1 <-  3
b2 <-  4

x1 <-  5
x2 <-  6

y <-  b0 + b1*x1^2 + b2*x2
y

class(b0)
class(y)
```


```{r}
solve <- function(x1, x2) {
  b0 <-  2
  b1 <-  3
  b2 <-  4
  y <-  b0 + b1*x1^2 + b2*x2
  return(y)
}

y2 <- solve(5, 6)


y2
class(solve)
class(y2)
```

seq function and vectors

```{r}
seq(from = 1, to = 10)
seq(from =1, by = 3, length = 5)

#Creating vectors
vec <- c(1,2,3,4)
```

Loops

```{r}
for (i in 1:5) {
  print(i)
}
```

Exercise:

Find the sum of the first 100 numbers.

```{r}
sum <- 0
for (i in 1:100) {
  sum <- sum + i
}
sum
```

```{r}
getSum <- function(N) {
  N*(N+1)/2
}

getSum(100)
```

```{r}
sum(1:100)
```

Get the sum of the numbers divisible by 3, upto one million.

```{r}
sum(seq(3, 1000000, by = 3))

sum <- 0
for (i in 1:1000000) {
  if (i %% 3 == 0) {
    sum <- sum + i
  }
}

```

Dataframes

```{r}
data(murders)
head(murders)
View(murders)

names(murders)
str(murders)

#The commented code below will not work in R Notebooks.

#The accessor $

murders$state
length(murders$state)
class(murders$state)
class(murders$region)
levels(murders$region)
```
```{r}
library(readr)
murders <- read_csv("murders.csv")
```

Creating dataframe
```{r}
dataFrame = data.frame(a = 1:6, b = 2:7)

# Reassignment
dataFrame <-  dataFrame %>% mutate(c = a + b)
```






