---
title: "R Notebook"
output: html_notebook
---

Now we are going to import Murders data and visualize it.

```{r}
library(tidyverse)
library(dslabs)
data("murders")
```

Now we want to find the states with the highest rates
```{r}
m1 <- murders %>% mutate(rate = total / population * 1e6) %>% select(state, rate) %>% arrange(-rate) %>% head(10)
```

```{r}
murders %>% select(total) %>% hist()
```


```{r}
murders$total %>% hist()

boxplot(murders$total)

```

```{r}
murders2 <- murders %>% mutate(pop = log10(population))

ggplot(data = murders, aes(x = population, y = total)) + 
  geom_point(aes(color = region)) + 
  geom_smooth(method = "lm") + scale_x_log10() + scale_y_log10()
```

```{r}
ggplot(data = murders2, aes(x = pop, y = total)) + 
  geom_point(aes(color = region)) + 
  geom_smooth(method = "lm")
```


```{r}
ggplot(data = murders, aes(x = population, y = total)) + 
  geom_point(color = "blue", size = 3) + 
  geom_smooth(method = "lm", se = FALSE) + scale_x_log10() + scale_y_log10()
```

```{r}
ggplot(data = murders, aes(x = population/10^6, y = total)) + 
  geom_point(size = 3, aes(col = region)) +
  geom_text(label = "a")
```




```{r}
ggplot(data = murders, aes(x = population/10^6, y = total)) + 
  geom_point(size = 3, aes(col = region)) +
  geom_text_repel(aes(label = abb)) +
  geom_smooth(method = "lm", se = FALSE, linewidth = 1, col = 'grey', linetype = 2)+
  scale_x_log10() +
  scale_y_log10() +
  xlab("Populations in millions (log scale)") + 
  ylab("Total number of murders (log scale)") +
  ggtitle("US Gun Murders in 2010") + theme_economist()

```









