---
title: "R Journey"
output: html_notebook
---

# Gapminder

## Data visualization Part 1

Loading the libraries

```{r warning=FALSE}
library(tidyverse)
library(dslabs)
```

Loading data

```{r}
data("gapminder")

```

EDA

```{r}
str(gapminder)
```

## Life Expectancy vs Fertility Rate in 1962

```{r}
gapminder %>% 
  select(country, fertility, life_expectancy, year, continent, gdp) %>% 
  filter(year == 1962) %>% ggplot(aes(x = life_expectancy, y = fertility, col = continent, size = gdp)) + geom_point() + ggtitle("Life Expectancy vs Fertility Rate in 1962")

```


## Life Expectancy vs Fertility Rate in 2012

```{r}
gapminder %>% 
  select(country, fertility, life_expectancy, year, continent, gdp) %>% 
  filter(year == 2012) %>% ggplot(aes(x = life_expectancy, y = fertility, col = continent)) + geom_point() + ggtitle("Life Expectancy vs Fertility Rate in 1962")
```

## Comparison

```{r}

gapminder %>% 
  select(country, fertility, life_expectancy, year, continent) %>% 
  filter(year == 1962 | year == 2012) %>%  
  ggplot(aes(x = life_expectancy, y = fertility, col = continent)) + geom_point() + ggtitle("Life Expectancy vs Fertility Rate in 1962 and 2012") + facet_wrap(~year) +
  theme_bw()

```

```{r}
filter(dslabs::gapminder, year %in% seq(1962, 2012,4)) |>
  ggplot( aes(fertility, life_expectancy, color = continent)) +
  geom_point(size = 3) + facet_wrap(~year, ncol =  4) + theme_bw()
```


```{r}
library(gganimate)

plt <- dslabs::gapminder  %>% ggplot(aes(x = fertility, y=life_expectancy, size = population, colour = continent)) +
    geom_point( alpha = 0.7) +
    scale_size(range = c(2, 12)) +
    scale_x_log10() +
    transition_time(year) +
    labs(title = "Year: {frame_time}") + theme_minimal()
```


```{r}
dslabs::gapminder %>% filter(year == 2000) %>% 
  ggplot(aes(x = gdp, 
             y=life_expectancy)) +
  geom_point(aes(col = continent)) +
  scale_x_log10()
```




```{r message=TRUE, warning=FALSE}
dslabs::gapminder %>% filter(year == 2000) %>% 
  ggplot(aes(x = gdp, 
             y=life_expectancy, 
             size = population)) +
  geom_point(aes(color = continent)) +
  scale_x_log10() +
  geom_smooth(method = "lm")
```

```{r}
  dslabs::gapminder %>% filter(year %in% (1962, 1980, 1990, 2000)) %>% 
    ggplot(aes(x = gdp, 
               y=life_expectancy, 
               size = population)) +
    geom_smooth(method = 'lm') +
    geom_point(aes(color = continent)) +
    scale_x_log10 ( ) +
    facet_wrap(~year)
```

```{r}
s <- state.region
class(s)
```

```{r}

state_data <- data.frame(state_name = state.name, 
                         state_region = state.region, 
                         state_abb = state.abb)

head(state_data)
```

```{r}
table(state.region)
```

```{r}
table(state_data$state_region) %>% prop.table()

```


```{r}
heights %>% ggplot(aes(height,  fill = sex)) + geom_density(alpha = 0.4)
```

```{r}
set.seed(10)
sim <- rnorm(1e6, mean = 0, sd = 1)
mean(sim)
```

```{r}
sd(sim)
```

```{r}
mean(sim <= 0)
```
```{r}
mean(sim >= 1)
```

```{r}
pnorm(3) - pnorm(-3)
```

```{r}
heights %>% 
  ggplot(aes(y = height, fill = sex, x= sex)) + 
  geom_boxplot(alpha = 0.4) + stat_compare_means(method = 't.test')
```
```{r}
males <- heights %>% filter(sex == "Male")

str(males)
mean(males$height)

females <- heights %>% filter(sex == "Female")
mean(females$height)

t.test(females$height, males$height)

mean(females$height) - mean(males$height)
```














